version: '2.5'
# version: '3.5' с новой версией не работает
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    build: .
    container_name: openvpn
    ports:
      - "1194:1194/tcp"
    restart: always
    volumes:
     - ./data:/etc/openvpn
    network_mode: bridge
    environment: 
      - TZ=Europe/Moscow