version: "3.5"
    services: 
        min_vpn:
            build:
                context: .
                dockerfile: dockerfile
            cap_add:
                - NET_ADMIN
            network_mode: bridge